# Generated by Django 4.1.7 on 2023-02-20 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField()),
            ],
            options={
                'db_table': 'pass_coords',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter_level', models.CharField(blank=True, max_length=3)),
                ('summer_level', models.CharField(blank=True, max_length=3)),
                ('autumn_level', models.CharField(blank=True, max_length=3)),
                ('spring_level', models.CharField(blank=True, max_length=3)),
            ],
            options={
                'db_table': 'pass_level',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fam', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('otc', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'pass_user',
            },
        ),
        migrations.CreateModel(
            name='PassAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('beauty_title', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('other_titles', models.CharField(max_length=255)),
                ('connect', models.CharField(blank=True, max_length=255)),
                ('add_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('new', 'новая заявка'), ('pending', 'на рассмотрении'), ('accepted', 'заявка принята'), ('rejected', 'заявка отклонена')], default='new', max_length=8)),
                ('coords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pass.coords')),
                ('levels', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='pass.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pass.user')),
            ],
            options={
                'db_table': 'pass_passadded',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=20)),
                ('data', models.BinaryField()),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pass.passadded')),
            ],
            options={
                'db_table': 'pass_images',
            },
        ),
    ]
